DROP TABLE tb_category CASCADE;
DROP TABLE tb_product CASCADE;
DROP TABLE tb_product_category;

create table tb_category (id int8 generated by default as identity, name varchar(255), primary key (id));
create table tb_product (id int8 generated by default as identity, name varchar(255), price float8, primary key (id));
create table tb_product_category (product_id int8 not null, category_id int8 not null, primary key (product_id, category_id));
alter table if exists tb_product_category add constraint FK5r4sbavb4nkd9xpl0f095qs2a foreign key (category_id) references tb_category;
alter table if exists tb_product_category add constraint FKgbof0jclmaf8wn2alsoexxq3u foreign key (product_id) references tb_product;
INSERT INTO tb_product (name, price) VALUES ('Computador', 2000.00);
INSERT INTO tb_product (name, price) VALUES ('Impressora', 800.00);
INSERT INTO tb_product (name, price) VALUES ('Mouse', 80.00);
INSERT INTO tb_category (name) VALUES ('Informática');
INSERT INTO tb_category (name) VALUES ('Escritório');
INSERT INTO tb_product_category (category_id, product_id) VALUES (1, 1);
INSERT INTO tb_product_category (category_id, product_id) VALUES (1, 2);
INSERT INTO tb_product_category (category_id, product_id) VALUES (1, 3);
INSERT INTO tb_product_category (category_id, product_id) VALUES (2, 2);

DROP TABLE tb_state CASCADE;
DROP TABLE tb_city CASCADE;

create table tb_state (id int8 generated by default as identity, name varchar(255), primary key (id));
create table tb_city (id int8 generated by default as identity, name varchar(255), state_id int8, primary key (id));
alter table if exists tb_city add constraint FK1rn7oty4mwqviyw8vk67crapo foreign key (state_id) references tb_state;
INSERT INTO tb_state (name) VALUES ('Minas Gerais');
INSERT INTO tb_state (name) VALUES ('São Paulo');
INSERT INTO tb_city (name, state_id) VALUES ('Uberlândia', 1);
INSERT INTO tb_city (name, state_id) VALUES ('São Paulo', 2);
INSERT INTO tb_city (name, state_id) VALUES ('Campinas', 2);


DROP TABLE tb_customer CASCADE;
DROP TABLE tb_phone CASCADE;

create table tb_customer (id int8 generated by default as identity, cpf_ou_cnpj varchar(255), email varchar(255), name varchar(255), type int4, primary key (id));
create table tb_phone (customer_id int8 not null, phone varchar(255));
alter table if exists tb_phone add constraint FKtip8d4q14yei5oq09x2dvp5tj foreign key (customer_id) references tb_customer;
INSERT INTO tb_customer (name, email, cpf_ou_cnpj, type) VALUES ('Maria Silva', 'maria@gmail.com', '36378912377', 1);
INSERT INTO tb_phone (customer_id, phone) VALUES (1, '27363323');
INSERT INTO tb_phone (customer_id, phone) VALUES (1, '93939393');

DROP TABLE tb_address CASCADE;

create table tb_address (id int8 generated by default as identity, complement varchar(255), district varchar(255), num varchar(255), public_place varchar(255), zip_code varchar(255), city_id int8, customer_id int8, primary key (id));
alter table if exists tb_address add constraint FKpm4x3qy2wea2p4ea7bs217nr5 foreign key (city_id) references tb_city;
alter table if exists tb_address add constraint FKt748w6ukdh6x4926sbd0bbjlg foreign key (customer_id) references tb_customer;
INSERT INTO tb_address (public_place, num, complement, district, zip_code, customer_id, city_id) VALUES ('Rua Flores', '300', 'Apto 303', 'Jardim', '38220534', 1, 1);
INSERT INTO tb_address (public_place, num, complement, district, zip_code, customer_id, city_id) VALUES  ('Rua Matos', '420', 'Apto 1402', 'Palhoça', '38212344', 1, 2);