DROP TABLE categoria CASCADE;
DROP TABLE produto CASCADE;
DROP TABLE produto_categoria;

create table categoria (id int8 generated by default as identity, nome varchar(255), primary key (id));
create table produto (id int8 generated by default as identity, nome varchar(255), preco float8, primary key (id));
create table produto_categoria (produto_id int8 not null, categoria_id int8 not null, primary key (produto_id, categoria_id));
alter table if exists produto_categoria add constraint FK5r4sbavb4nkd9xpl0f095qs2a foreign key (categoria_id) references categoria;
alter table if exists produto_categoria add constraint FKgbof0jclmaf8wn2alsoexxq3u foreign key (produto_id) references produto;
INSERT INTO produto (nome, preco) VALUES ('Computador', 2000.00);
INSERT INTO produto (nome, preco) VALUES ('Impressora', 800.00);
INSERT INTO produto (nome, preco) VALUES ('Mouse', 80.00);
INSERT INTO categoria (nome) VALUES ('Informática');
INSERT INTO categoria (nome) VALUES ('Escritório');
INSERT INTO produto_categoria (categoria_id, produto_id) VALUES (1, 1);
INSERT INTO produto_categoria (categoria_id, produto_id) VALUES (1, 2);
INSERT INTO produto_categoria (categoria_id, produto_id) VALUES (1, 3);
INSERT INTO produto_categoria (categoria_id, produto_id) VALUES (2, 2);

DROP TABLE estado CASCADE;
DROP TABLE cidade CASCADE;

create table estado (id int8 generated by default as identity, nome varchar(255), primary key (id));
create table cidade (id int8 generated by default as identity, nome varchar(255), estado_id int8, primary key (id));
alter table if exists cidade add constraint FK1rn7oty4mwqviyw8vk67crapo foreign key (estado_id) references estado;
INSERT INTO estado (nome) VALUES ('Minas Gerais');
INSERT INTO estado (nome) VALUES ('São Paulo');
INSERT INTO cidade (nome, estado_id) VALUES ('Uberlândia', 1);
INSERT INTO cidade (nome, estado_id) VALUES ('São Paulo', 2);
INSERT INTO cidade (nome, estado_id) VALUES ('Campinas', 2);


DROP TABLE cliente CASCADE;
DROP TABLE telefone CASCADE;

create table cliente (id int8 generated by default as identity, cpf_ou_cnpj varchar(255), email varchar(255), nome varchar(255), tipo int4, primary key (id));
create table telefone (cliente_id int8 not null, telefones varchar(255));
alter table if exists telefone add constraint FKtip8d4q14yei5oq09x2dvp5tj foreign key (cliente_id) references cliente;
INSERT INTO cliente (nome, email, cpf_ou_cnpj, tipo) VALUES ('Maria Silva', 'maria@gmail.com', '36378912377', 1);
INSERT INTO telefone (cliente_id, telefones) VALUES (1, '27363323');
INSERT INTO telefone (cliente_id, telefones) VALUES (1, '93939393');

DROP TABLE endereco CASCADE;

create table endereco (id int8 generated by default as identity, logradouro varchar(255), numero varchar(255), complemento varchar(255), bairro varchar(255), cep varchar(255), cidade_id int8, cliente_id int8, primary key (id));
alter table if exists endereco add constraint FKpm4x3qy2wea2p4ea7bs217nr5 foreign key (cidade_id) references cidade;
alter table if exists endereco add constraint FKt748w6ukdh6x4926sbd0bbjlg foreign key (cliente_id) references cliente;
INSERT INTO endereco (logradouro, numero, complemento, bairro, cep, cliente_id, cidade_id) VALUES ('Rua Flores', '300', 'Apto 303', 'Jardim', '38220534', 1, 1);
INSERT INTO endereco (logradouro, numero, complemento, bairro, cep, cliente_id, cidade_id) VALUES  ('Rua Matos', '420', 'Apto 1402', 'Palhoça', '38212344', 1, 2);
